#!/usr/bin/env python3
import argparse
import hashlib
import json
from datetime import datetime, timezone
from pathlib import Path
from urllib.parse import quote


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def asset_url(repo: str, tag: str, filename: str) -> str:
    # Filenames are generated by our workflow from fixed safe tokens.
    return f"https://github.com/{repo}/releases/download/{quote(tag, safe='')}/{quote(filename, safe='')}"


def file_spec(identifier: str, kind: str, path: Path, repo: str, tag: str) -> dict:
    if not path.is_file() or path.stat().st_size <= 0:
        raise SystemExit(f"Missing or empty release asset: {path}")
    return {
        "id": identifier,
        "kind": kind,
        "fileName": path.name,
        "url": asset_url(repo, tag, path.name),
        "sha256": sha256(path),
        "bytes": path.stat().st_size,
        "schemaVersion": 1,
        "required": True,
    }


def main() -> None:
    parser = argparse.ArgumentParser(description="Create RockMap Alpha 2 basemap-test manifest")
    parser.add_argument("--repo", required=True, help="GitHub repository as OWNER/REPO")
    parser.add_argument("--tag", required=True)
    parser.add_argument("--source-date", required=True, help="Protomaps daily build date YYYYMMDD")
    parser.add_argument("--maxzoom", type=int, required=True)
    parser.add_argument("--bbox", required=True)
    parser.add_argument("--base", type=Path, required=True)
    parser.add_argument("--style", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()

    if args.repo.count("/") != 1 or any(c.isspace() for c in args.repo):
        raise SystemExit("--repo must be OWNER/REPO")
    if not (0 <= args.maxzoom <= 20):
        raise SystemExit("--maxzoom is outside the allowed range")
    if len(args.source_date) != 8 or not args.source_date.isdigit():
        raise SystemExit("--source-date must be YYYYMMDD")

    published_at = datetime.now(timezone.utc).replace(microsecond=0).isoformat().replace("+00:00", "Z")
    manifest = {
        "manifestVersion": 1,
        "styleSchemaVersion": 1,
        "minimumAppVersionCode": 1,
        "pack": "Colorado Protomaps/OpenStreetMap basemap test",
        "version": f"protomaps-{args.source_date}-colorado-z{args.maxzoom}",
        "publishedAt": published_at,
        "status": "basemap_test",
        "message": "Basemap test only. NOT VERIFIED FOR NAVIGATION. Land status, mining claims, and offline labels are not included yet.",
        "source": {
            "provider": "Protomaps Basemap",
            "openStreetMapSnapshot": args.source_date,
            "bbox": args.bbox,
            "maxzoom": args.maxzoom,
            "attribution": "© OpenStreetMap contributors · Protomaps"
        },
        "files": [
            file_spec("style", "style", args.style, args.repo, args.tag),
            file_spec("base", "pmtiles", args.base, args.repo, args.tag),
        ],
    }

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(json.dumps(manifest, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()
