#!/usr/bin/env python3
"""Causal debugger v1: attribution, watchdogs, surface audits, and transparent touch tracing.

This pass is diagnostic-only. It may add logging calls, transparent dispatchTouchEvent wrappers,
weak View registrations and watchdog observations. It must not change application state, move UI,
invoke app actions, alter return values, or retry/suppress application callbacks.
"""
from pathlib import Path
import os

ROOT = Path(__file__).resolve().parents[1]


def text(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def replace_once(path: Path, marker: str, old: str, new: str, label: str) -> None:
    current = text(path)
    if marker in current:
        print(f"{label}: already present")
        return
    count = current.count(old)
    if count != 1:
        raise RuntimeError(
            f"{label}: expected exactly one match in {path.relative_to(ROOT)}, found {count}"
        )
    path.write_text(current.replace(old, new, 1), encoding="utf-8")
    print(f"{label}: injected")


def ensure_import(path: Path, import_line: str, after_line: str, label: str) -> None:
    current = text(path)
    if import_line in current:
        print(f"{label}: already present")
        return
    if after_line not in current:
        raise RuntimeError(f"{label}: import anchor missing in {path.relative_to(ROOT)}")
    path.write_text(current.replace(after_line, after_line + import_line, 1), encoding="utf-8")
    print(f"{label}: injected")


def generate_build_info() -> None:
    sha = os.environ.get("GITHUB_SHA", "unknown").strip() or "unknown"
    run = os.environ.get("GITHUB_RUN_NUMBER", "local").strip() or "local"
    path = ROOT / "app/src/main/java/com/rockmap/app/TourDebugBuildInfo.java"
    path.write_text(
        "package com.rockmap.app;\n\n"
        "/** Generated by the tour-debug injector; diagnostic identity only. */\n"
        "public final class TourDebugBuildInfo {\n"
        f"    public static final String GIT_SHA = \"{sha}\";\n"
        f"    public static final String WORKFLOW_RUN = \"{run}\";\n"
        "    public static final String INJECTOR = \"causal-debugger-v1\";\n"
        "    private TourDebugBuildInfo() {}\n"
        "}\n",
        encoding="utf-8",
    )
    print("generated TourDebugBuildInfo")


def patch_tour_debug_log(path: Path) -> None:
    replace_once(
        path,
        "causal-debug-session-fields",
        '    private static final String FILE_NAME = "RockMap-Tour-Debug.txt";\n',
        '    private static final String FILE_NAME = "RockMap-Tour-Debug.txt";\n'
        '    private static final String DEBUG_SCHEMA = TourDebugCausality.SCHEMA;\n'
        '    private static final String SESSION_ID = "S" + Long.toHexString(System.currentTimeMillis())\n'
        '            + "-" + android.os.Process.myPid(); // marker: causal-debug-session-fields\n',
        "TourDebugLog session fields",
    )

    replace_once(
        path,
        "causal-debug-pref-listeners",
        '''        mainListener = (prefs, key) ->
                record("MAIN_STATE", "changed=" + clean(key, 80) + " " + mainSnapshot());
        fieldListener = (prefs, key) ->
                record("FIELD_STATE", "changed=" + clean(key, 80) + " " + fieldSnapshot());
''',
        '''        mainListener = (prefs, key) -> {
            record("MAIN_STATE", "changed=" + clean(key, 80) + " " + mainSnapshot());
            if ("tour_step".equals(key) || "tour_state".equals(key)) {
                TourDebugCausality.onMainTourStepChanged(
                        mainPrefs.getInt("tour_step", 1),
                        mainPrefs.getString("tour_state", "not_offered"));
            }
        };
        fieldListener = (prefs, key) ->
                record("FIELD_STATE", "changed=" + clean(key, 80) + " " + fieldSnapshot());
        // marker: causal-debug-pref-listeners
''',
        "causal tour preference listeners",
    )

    replace_once(
        path,
        "causal-debug-lifecycle-resumed",
        '''                        @Override public void onActivityResumed(Activity activity) {
                            recordImportant("ACTIVITY",
''',
        '''                        @Override public void onActivityResumed(Activity activity) {
                            TourDebugCausality.onActivityResumed(activity);
                            recordImportant("ACTIVITY",
                            // marker: causal-debug-lifecycle-resumed
''',
        "causal lifecycle resume hook",
    )

    replace_once(
        path,
        "causal-debug-lifecycle-destroyed",
        '''                        @Override public void onActivityDestroyed(Activity activity) {
                            recordImportant("ACTIVITY",
''',
        '''                        @Override public void onActivityDestroyed(Activity activity) {
                            TourDebugCausality.onActivityDestroyed(activity);
                            recordImportant("ACTIVITY",
                            // marker: causal-debug-lifecycle-destroyed
''',
        "causal lifecycle destroy hook",
    )

    replace_once(
        path,
        "causal-debug-process-identity",
        '''        recordImportant("PROCESS_START",
                "version=" + safeVersion()
                        + " code=" + safeVersionCode()
''',
        '''        recordImportant("PROCESS_START",
                "debugSchema=" + DEBUG_SCHEMA
                        + " session=" + SESSION_ID
                        + " git=" + TourDebugBuildInfo.GIT_SHA
                        + " workflowRun=" + TourDebugBuildInfo.WORKFLOW_RUN
                        + " injector=" + TourDebugBuildInfo.INJECTOR
                        + " version=" + safeVersion()
                        + " code=" + safeVersionCode()
                        // marker: causal-debug-process-identity
''',
        "debugger build/session identity",
    )

    replace_once(
        path,
        "causal-debug-coach-request-hook",
        '''    public static void coachRequest(Activity activity, long generation, int step, int total,
                                    String title, String requiredAction, View target) {
        recordImportant("COACH_REQUEST",
''',
        '''    public static void coachRequest(Activity activity, long generation, int step, int total,
                                    String title, String requiredAction, View target) {
        TourDebugCausality.onCoachRequest(activity, step, generation);
        recordImportant("COACH_REQUEST",
        // marker: causal-debug-coach-request-hook
''',
        "coach request causal hook",
    )

    replace_once(
        path,
        "causal-debug-coach-shown-hook",
        '''    public static void coachShown(Activity activity, long generation, int step, int total,
                                  String title, View target, boolean dialogHost) {
        recordImportant("COACH_SHOWN",
''',
        '''    public static void coachShown(Activity activity, long generation, int step, int total,
                                  String title, View target, boolean dialogHost) {
        TourDebugCausality.onCoachShown(activity, step, generation);
        recordImportant("COACH_SHOWN",
        // marker: causal-debug-coach-shown-hook
''',
        "coach shown causal hook",
    )

    replace_once(
        path,
        "causal-debug-public-event-api",
        '''    /** Observational compass diagnostics. Does not alter heading, sensors, map state, or lifecycle. */
''',
        '''    /** Structured causal/debugger event. Diagnostic-only. */
    public static void causalEvent(String event, String detail) {
        recordImportant(clean(event, 60), clean(detail, 5000));
    } // marker: causal-debug-public-event-api

    /** Observational compass diagnostics. Does not alter heading, sensors, map state, or lifecycle. */
''',
        "public causal debugger event API",
    )

    replace_once(
        path,
        "causal-debug-line-prefix",
        '''        String line = timestamp
                + " | +" + elapsed + "ms"
                + " | #" + sequence
                + " | " + clean(type, 60)
                + " | " + clean(detail, 5000)
                + "\\n";
''',
        '''        String line = timestamp
                + " | +" + elapsed + "ms"
                + " | #" + sequence
                + " | session=" + SESSION_ID
                + " | schema=" + DEBUG_SCHEMA
                + " | " + clean(type, 60)
                + " | " + clean(TourDebugCausality.contextSummary(), 700)
                + " | " + clean(detail, 5000)
                + "\\n"; // marker: causal-debug-line-prefix
''',
        "causal/session prefix on every line",
    )


def patch_causality(path: Path) -> None:
    replace_once(
        path,
        "causal-debug-child-scope-api",
        '''    public static Scope begin(Activity activity, String origin, String action, String target) {
        Cause previous = CURRENT.get();
        return beginWithParent(activity, origin, action, target,
                previous == null ? "" : previous.id, previous);
    }

''',
        '''    public static Scope begin(Activity activity, String origin, String action, String target) {
        Cause previous = CURRENT.get();
        return beginWithParent(activity, origin, action, target,
                previous == null ? "" : previous.id, previous);
    }

    public static Scope beginChild(Activity activity, String origin, String action,
                                   String target, String parentCauseId) {
        return beginWithParent(activity, origin, action, target,
                parentCauseId == null ? "" : parentCauseId, CURRENT.get());
    } // marker: causal-debug-child-scope-api

''',
        "causal child-scope API",
    )


def patch_invariant_monitor(path: Path) -> None:
    replace_once(
        path,
        "causal-debug-invariant-failure-snapshot",
        '''        TourDebugLog.mainTourAction(activity,
                condition ? "UI_INVARIANT_OK" : "UI_INVARIANT_FAIL",
                "id=" + id + " invariant=" + clean(name, 120)
                        + " " + clean(detail, 900));
        return condition;
''',
        '''        TourDebugLog.mainTourAction(activity,
                condition ? "UI_INVARIANT_OK" : "UI_INVARIANT_FAIL",
                "id=" + id + " invariant=" + clean(name, 120)
                        + " " + clean(detail, 900));
        if (!condition) {
            TourDebugCausality.finding(activity, "ERROR",
                    "UI_INVARIANT_" + clean(name, 80),
                    "transition=" + id + " " + clean(detail, 900));
        }
        // marker: causal-debug-invariant-failure-snapshot
        return condition;
''',
        "invariant failure causal finding",
    )

    replace_once(
        path,
        "causal-debug-observational-frame-monitor",
        '''        target.requestLayout();
        target.invalidate();
        scheduler.requestLayout();
        scheduler.invalidate();

''',
        '''        // Diagnostic-only: do not request layout/invalidate merely to make the observed
        // condition become true. The debugger waits for the app's own next frame.
        // marker: causal-debug-observational-frame-monitor

''',
        "remove debugger-induced layout mutation",
    )

    replace_once(
        path,
        "causal-debug-frame-parent",
        '''        final long armedAt = SystemClock.elapsedRealtime();
        state(activity, transitionId, "UI_FRAME_ARMED",
''',
        '''        final long armedAt = SystemClock.elapsedRealtime();
        final String armCause = TourDebugCausality.currentCauseId();
        state(activity, transitionId, "UI_FRAME_ARMED",
        // marker: causal-debug-frame-parent
''',
        "capture frame parent cause",
    )

    replace_once(
        path,
        "causal-debug-frame-scope-open",
        '''        holder[0] = () -> {
            if (!finished.compareAndSet(false, true)) return true;
''',
        '''        holder[0] = () -> {
            try (TourDebugCausality.Scope ignored = TourDebugCausality.beginChild(
                    activity, TourDebugCausality.ORIGIN_FRAME,
                    "predraw:" + clean(label, 100), "transition=" + transitionId, armCause)) {
            if (!finished.compareAndSet(false, true)) return true;
            // marker: causal-debug-frame-scope-open
''',
        "frame callback causal scope",
    )

    replace_once(
        path,
        "causal-debug-frame-result-hook",
        '''            invariant(activity, transitionId, "target_visible_on_committed_frame", visible,
                    "label=" + clean(label, 100));
            if (visible) {
''',
        '''            invariant(activity, transitionId, "target_visible_on_committed_frame", visible,
                    "label=" + clean(label, 100));
            TourDebugCausality.onFrameResult(activity, label, visible, transitionId);
            // marker: causal-debug-frame-result-hook
            if (visible) {
''',
        "frame result causal hook",
    )

    replace_once(
        path,
        "causal-debug-frame-scope-close",
        '''            return true;
        };
        if (observer.isAlive()) observer.addOnPreDrawListener(holder[0]);
''',
        '''            return true;
            }
        }; // marker: causal-debug-frame-scope-close
        if (observer.isAlive()) observer.addOnPreDrawListener(holder[0]);
''',
        "frame callback causal scope close",
    )

    replace_once(
        path,
        "causal-debug-frame-timeout-hook",
        '''            state(activity, transitionId, "UI_FRAME_STALL",
                    "label=" + clean(label, 100) + " reason=no_predraw_within_750ms"
                            + " target=" + targetSummary(target));
            invariant(activity, transitionId, "next_frame_arrived", false,
''',
        '''            state(activity, transitionId, "UI_FRAME_STALL",
                    "label=" + clean(label, 100) + " reason=no_predraw_within_750ms"
                            + " target=" + targetSummary(target));
            TourDebugCausality.onFrameResult(activity, label, false, transitionId);
            // marker: causal-debug-frame-timeout-hook
            invariant(activity, transitionId, "next_frame_arrived", false,
''',
        "frame timeout causal hook",
    )


def add_touch_override(path: Path, style: str, label: str) -> None:
    marker = f"causal-debug-touch-{style}"
    if marker in text(path):
        print(f"{label}: already present")
        return
    if style == "main":
        anchor = '''    @Override
    protected void onCreate(Bundle savedInstanceState) {
'''
        insert = '''    @Override
    public boolean dispatchTouchEvent(android.view.MotionEvent event) {
        TourDebugCausality.DispatchToken trace = TourDebugCausality.beforeDispatchTouch(this, event);
        try {
            return super.dispatchTouchEvent(event);
        } finally {
            TourDebugCausality.afterDispatchTouch(this, event, trace);
        }
    } // marker: causal-debug-touch-main

''' + anchor
    elif style == "field":
        anchor = '''    @Override protected void onCreate(Bundle state) {
'''
        insert = '''    @Override public boolean dispatchTouchEvent(android.view.MotionEvent event) {
        com.rockmap.app.TourDebugCausality.DispatchToken trace =
                com.rockmap.app.TourDebugCausality.beforeDispatchTouch(this, event);
        try {
            return super.dispatchTouchEvent(event);
        } finally {
            com.rockmap.app.TourDebugCausality.afterDispatchTouch(this, event, trace);
        }
    } // marker: causal-debug-touch-field

''' + anchor
    else:
        anchor = '''    @Override protected void onCreate(Bundle state) {
'''
        insert = '''    @Override public boolean dispatchTouchEvent(android.view.MotionEvent event) {
        com.rockmap.app.TourDebugCausality.DispatchToken trace =
                com.rockmap.app.TourDebugCausality.beforeDispatchTouch(this, event);
        try {
            return super.dispatchTouchEvent(event);
        } finally {
            com.rockmap.app.TourDebugCausality.afterDispatchTouch(this, event, trace);
        }
    } // marker: causal-debug-touch-research

''' + anchor
    replace_once(path, marker, anchor, insert, label)


def patch_main_tour(path: Path) -> None:
    replace_once(
        path,
        "causal-debug-tour-scheduler",
        '''        scheduler.post(() -> showGuidedTourCoachWhenReady(expectedStep, generation, 0));
''',
        '''        scheduler.post(TourDebugCausality.wrapScheduled(this,
                TourDebugCausality.ORIGIN_TOUR,
                "show-coach-ready-step-" + expectedStep,
                "tourGeneration=" + generation,
                () -> showGuidedTourCoachWhenReady(expectedStep, generation, 0)));
        // marker: causal-debug-tour-scheduler
''',
        "tour coach scheduler causal wrapper",
    )

    replace_once(
        path,
        "causal-debug-tour-retry-scheduler",
        '''        scheduler.postDelayed(
                () -> showGuidedTourCoachWhenReady(expectedStep, generation, attempt + 1), 40L);
''',
        '''        scheduler.postDelayed(TourDebugCausality.wrapScheduled(this,
                TourDebugCausality.ORIGIN_TOUR,
                "retry-coach-step-" + expectedStep,
                "tourGeneration=" + generation + ",attempt=" + (attempt + 1),
                () -> showGuidedTourCoachWhenReady(expectedStep, generation, attempt + 1)), 40L);
        // marker: causal-debug-tour-retry-scheduler
''',
        "tour retry scheduler causal wrapper",
    )

    replace_once(
        path,
        "causal-debug-step-gate",
        '''    private void showGuidedTourCoachWhenReady(int expectedStep, long generation, int attempt) {
        if (generation != guidedTourScheduleGeneration
''',
        '''    private void showGuidedTourCoachWhenReady(int expectedStep, long generation, int attempt) {
        TourDebugCausality.stepGate(this, expectedStep, attempt, "showGuidedTourCoachWhenReady");
        // marker: causal-debug-step-gate
        if (generation != guidedTourScheduleGeneration
''',
        "tour step readiness gate observation",
    )

    replace_once(
        path,
        "causal-debug-step-preparation",
        '''    private void prepareMappedResearchTourPresentation(int step) {
        if (mapView == null || (step != GuidedTourState.STEP_CONTEXT_CONTROLS
''',
        '''    private void prepareMappedResearchTourPresentation(int step) {
        TourDebugCausality.stepPreparation(this, step, "mapped-research-presentation");
        // marker: causal-debug-step-preparation
        if (mapView == null || (step != GuidedTourState.STEP_CONTEXT_CONTROLS
''',
        "mapped Research step preparation observation",
    )

    replace_once(
        path,
        "causal-debug-clean-start-audit",
        '''        UiInvariantMonitor.state(this, transition, "TOUR_PREPARE_COMPLETE",
                "origin=" + origin + " clean=" + clean);
        return clean;
''',
        '''        UiInvariantMonitor.state(this, transition, "TOUR_PREPARE_COMPLETE",
                "origin=" + origin + " clean=" + clean);
        TourDebugSurfaceAudit.auditTourCleanStart(this, origin);
        // marker: causal-debug-clean-start-audit
        return clean;
''',
        "tour clean-start surface audit",
    )


def patch_research_panel(path: Path) -> None:
    ensure_import(path,
                  "import com.rockmap.app.TourDebugSurfaceAudit;\n",
                  "import com.rockmap.app.RockMapDragHandle;\n",
                  "Research surface audit import")
    replace_once(
        path,
        "causal-debug-research-surface-observe",
        '''    private void renderMode() {
''',
        '''    private void renderMode() {
        if (panel != null) {
            TourDebugSurfaceAudit.observe(activity, "research.workspace", panel,
                    mode, false);
        }
        // marker: causal-debug-research-surface-observe
''',
        "Research workspace surface observation",
    )


def patch_prospecting_prompt(path: Path) -> None:
    ensure_import(path,
                  "import com.rockmap.app.TourDebugSurfaceAudit;\n",
                  "import com.rockmap.app.MainActivity;\n",
                  "Prospecting prompt surface audit import")
    replace_once(
        path,
        "causal-debug-prospecting-prompt-register",
        '''        root.addView(bar, params);
        bar.bringToFront();
''',
        '''        root.addView(bar, params);
        TourDebugSurfaceAudit.register(activity, "prospecting.saved-prompt", bar,
                "visible", false);
        // marker: causal-debug-prospecting-prompt-register
        bar.bringToFront();
''',
        "Prospecting saved prompt registration",
    )


def patch_coach_surface(path: Path) -> None:
    replace_once(
        path,
        "causal-debug-coach-surface-register",
        '''        card.setTag(TAG);
        card.setOrientation(LinearLayout.VERTICAL);
''',
        '''        card.setTag(TAG);
        TourDebugSurfaceAudit.register(activity, "tour.coach", card,
                "step=" + step, false);
        // marker: causal-debug-coach-surface-register
        card.setOrientation(LinearLayout.VERTICAL);
''',
        "guided coach surface registration",
    )


def patch_mapped_surface(path: Path) -> None:
    ensure_import(path,
                  "import com.rockmap.app.TourDebugSurfaceAudit;\n",
                  "import com.rockmap.app.MainActivity;\n",
                  "mapped surface audit import")
    replace_once(
        path,
        "causal-debug-mapped-surface-observe",
        '''    private void notifyPresentationReady(View anchor) {
''',
        '''    private void notifyPresentationReady(View anchor) {
        View displayedForDebug = getDisplayedContainer();
        if (displayedForDebug != null) {
            TourDebugSurfaceAudit.observe(activity, "mapped.research", displayedForDebug,
                    menuCollapsed ? "collapsed" : "expanded", false);
        }
        // marker: causal-debug-mapped-surface-observe
''',
        "mapped Research surface observation",
    )


def patch_field_surface(path: Path) -> None:
    ensure_import(path,
                  "import com.rockmap.app.TourDebugSurfaceAudit;\n",
                  "import com.rockmap.app.TourDebugLog;\n",
                  "Field surface audit import")
    replace_once(
        path,
        "causal-debug-field-surface-observe",
        '''        TourDebugLog.hudLifecycle(activity, "HUD_READY", renderGeneration, reason,
                expandedTool, measurement.size(), hud, requiredTarget, renderStarted);
''',
        '''        TourDebugLog.hudLifecycle(activity, "HUD_READY", renderGeneration, reason,
                expandedTool, measurement.size(), hud, requiredTarget, renderStarted);
        if (hud != null) {
            TourDebugSurfaceAudit.observe(activity, "field.hud", hud,
                    expandedTool == null ? "hidden" : "expanded:" + expandedTool, false);
        }
        if (collapsedTabs != null) {
            TourDebugSurfaceAudit.observe(activity, "field.collapsed-tools", collapsedTabs,
                    collapsedTabs.isShown() ? "visible" : "hidden", false);
        }
        if (fieldButton != null) {
            TourDebugSurfaceAudit.observe(activity, "field.entry", fieldButton,
                    fieldButton.isShown() ? "visible" : "hidden", true);
        }
        // marker: causal-debug-field-surface-observe
''',
        "Field HUD/collapsed surface observation",
    )


def main() -> int:
    log = ROOT / "app/src/main/java/com/rockmap/app/TourDebugLog.java"
    causality = ROOT / "app/src/main/java/com/rockmap/app/TourDebugCausality.java"
    invariant = ROOT / "app/src/main/java/com/rockmap/app/UiInvariantMonitor.java"
    main_activity = ROOT / "app/src/main/java/com/rockmap/app/MainActivity.java"
    field_activity = ROOT / "app/src/main/java/com/rockmap/app/field/FieldActivity.java"
    research_activity = ROOT / "app/src/main/java/com/rockmap/app/research/ResearchActivity.java"
    research_panel = ROOT / "app/src/main/java/com/rockmap/app/research/ResearchAreaPanelController.java"
    prospecting = ROOT / "app/src/main/java/com/rockmap/app/field/ProspectingAreaCreator.java"
    coach = ROOT / "app/src/main/java/com/rockmap/app/GuidedTourCoach.java"
    mapped = ROOT / "app/src/main/java/com/rockmap/app/map/MapContextCloseController.java"
    field_map = ROOT / "app/src/main/java/com/rockmap/app/field/FieldMapController.java"

    required = [log, causality, invariant, main_activity, field_activity, research_activity,
                research_panel, prospecting, coach, mapped, field_map]
    for path in required:
        if not path.is_file():
            raise RuntimeError(f"required file missing: {path.relative_to(ROOT)}")

    originals = {path: text(path) for path in required}
    build_info = ROOT / "app/src/main/java/com/rockmap/app/TourDebugBuildInfo.java"
    old_build_info = text(build_info) if build_info.is_file() else None
    try:
        generate_build_info()
        patch_tour_debug_log(log)
        patch_causality(causality)
        patch_invariant_monitor(invariant)
        add_touch_override(main_activity, "main", "MainActivity transparent touch tracing")
        add_touch_override(field_activity, "field", "FieldActivity transparent touch tracing")
        add_touch_override(research_activity, "research", "ResearchActivity transparent touch tracing")
        patch_main_tour(main_activity)
        patch_research_panel(research_panel)
        patch_prospecting_prompt(prospecting)
        patch_coach_surface(coach)
        patch_mapped_surface(mapped)
        patch_field_surface(field_map)

        # Scope guard: this pass may mention only diagnostic APIs in the injected markers. It must
        # never introduce direct state mutators as part of debugger instrumentation.
        forbidden_in_debug_classes = [
            ".performClick(", ".setVisibility(", ".bringToFront(", ".requestLayout(",
            ".invalidate(", "GuidedTourState.setStep(", "FieldMapState.set", "MapHudCoordinator.beforeExpand("
        ]
        for path in (causality, ROOT / "app/src/main/java/com/rockmap/app/TourDebugSurfaceAudit.java"):
            content = text(path)
            for token in forbidden_in_debug_classes:
                if token in content:
                    raise RuntimeError(
                        f"debugger scope guard failed: {path.relative_to(ROOT)} contains {token}"
                    )

        print("Causal tour debugger injection complete.")
        print("Scope: observational diagnostics only; no application behavior repair.")
        return 0
    except Exception:
        for path, content in originals.items():
            path.write_text(content, encoding="utf-8")
        if old_build_info is None:
            if build_info.exists():
                build_info.unlink()
        else:
            build_info.write_text(old_build_info, encoding="utf-8")
        print("Causal tour debugger injection rolled back after failure.")
        raise


if __name__ == "__main__":
    raise SystemExit(main())
